Based on notebook 6, for further experiments only knn, xgboost and linear svc will be considered.  

#convert reason to numbers  
{'Mau Serviço Prestado': 0,  
'Condições de entrega': 1,   
'Atraso de entrega': 2,   
'Enganos': 3}  

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler #fixed import

import nltk
import re
from langdetect import detect
from scipy.sparse import hstack
import gensim
from gensim.models import Word2Vec, KeyedVectors
from nltk import word_tokenize

In [2]:
df = pd.read_csv("D:\\MS DATA SCIENCE\\NLP TESE\\data\\data_processed_selected.csv")
df.head()

date                                              title  \
0  2021-10-11 12:26:32  CTT - Encomenda entregue danificada e com etiq...   
1  2021-08-31 23:20:15               CTT - Carta com certificado rasgado!   
2  2021-02-01 19:08:32  CTT - Encomenda registada que nunca chegou ao ...   
3  2018-04-19 09:04:34                                CTT - Correio Verde   
4  2019-07-04 10:20:41  CTT - Aviso de recepção da carta registada, pr...   

   reason                                        description     zone  \
0       0  Bom dia venho por este meio apresentar uma rec...   Lisboa   
1       1  - Boa Noite!\r\n\r\n- Venho por este meio recl...  Coimbra   
2       2  Boa tarde,\r\nNo dia 17 de Dezembro de 2020 en...   Aveiro   
3       2  Bom dia,\n\nPretendia esclarecer uma situação ...   Lisboa   
4       2  venho por este meio solicitar a vossa ajuda pa...    Porto   

                                     narrative_tfidf  \
0  bom dia venho meio apresentar reclamação ctt e...   
1  bom noite venho meio reclamar data ás durante ...   
2  bom tarde dia dezembro enviar encomenda França...   
3  bom dia pretender esclarecer situação ocorrer ...   
4  venho meio solicitar vosso ajudar saber onde e...   

                                narrative_embeddings  \
0  bom dia venho por este meio apresentar uma rec...   
1  - boa noite!\r\n\r\n- venho por este meio recl...   
2  boa tarde,\r\nno dia 00 de dezembro de 0000 en...   
3  bom dia,\n\npretendia esclarecer uma situação ...   
4  venho por este meio solicitar a vossa ajuda pa...   

                                      narrative_bert  \
0  Bom dia venho por este meio apresentar uma rec...   
1  - Boa Noite! Venho por este meio reclamar que ...   
2  Boa tarde, No dia 17 de Dezembro de 2020 envie...   
3  Bom dia, Pretendia esclarecer uma situação que...   
4  venho por este meio solicitar a vossa ajuda pa...   

                               narrative_tfidf_title  \
0  ctt encomenda entregar danificar etiqueta envi...   
1  ctt carta certificar rasgar bom noite venho me...   
2  ctt encomenda registar nunca chegar destine o ...   
3  ctt correio verde bom dia pretender esclarecer...   
4  ctt aviso recepção carta registar preciso urge...   

                                narrative_bert_title  ...  \
0  ctt - encomenda entregue danificada e com etiq...  ...   
1  ctt - carta com certificado rasgado!  - Boa No...  ...   
2  ctt - encomenda registada que nunca chegou ao ...  ...   
3  ctt - correio verde  Bom dia, Pretendia esclar...  ...   
4  ctt - aviso de recepção da carta registada, pr...  ...   

                                         tfidf_title  \
0  ctt encomenda entregar danificar etiqueta envi...   
1                        ctt carta certificar rasgar   
2      ctt encomenda registar nunca chegar destine o   
3                                  ctt correio verde   
4  ctt aviso recepção carta registar preciso urge...   

                                 title_tfidf_nolemma  \
0  ctt encomenda entregue danificada etiquetas en...   
1                      ctt carta certificado rasgado   
2       ctt encomenda registada nunca chegou destino   
3                                  ctt correio verde   
4  ctt aviso recepção carta registada preciso urg...   

                                              events  \
0  ['venho', 'apresentar', 'Enviei', 'destinado',...   
1  ['Venho', 'reclamar', 'deparei -me', 'continha...   
2  ['enviei', 'registado', 'vejo', 'chegou', 'sai...   
3  ['Pretendia esclarecer', 'ocorreu', 'desloquei...   
4  ['venho', 'solicitar', 'saber onde se encontra...   

                                            keywords  \
0  apresentar uma reclamação tinha caixa figura e...   
1  Lilia Pimentel certificado profissional passag...   
2  França em correio registado França em correio ...   
3  Pretendia esclarecer uma situação Pretendia es...   
4  papais para o centro pois preciso dele urgente...   

                                                locs 

In [3]:
df['reason'].unique()

array([0, 1, 2, 3], dtype=int64)

In [4]:
# Create a Counter object
class_counts = Counter(df['reason'])

# Access the counts of each class
for class_label, count in class_counts.items():
    print(f"Class {class_label}: {count/len(df)} samples")

Class 0: 0.3551493535443602 samples
Class 1: 0.09893000445831476 samples
Class 2: 0.4782880071333036 samples
Class 3: 0.0676326348640214 samples


In [8]:
# before
# {'Mau Serviço Prestado': 0,
# 'Condições de entrega': 1,
# 'Atraso de entrega': 2,
# 'Enganos': 3}

# Map classes to new groups 
# keys correspond to the original class labels, and the values correspond to the new class labels
class_mapping = {
    0: 0,
    1: 0,
    2: 1,
    3: 0
}

# Step 3: Update the labels
df['reason_binary'] = df['reason'].map(class_mapping)

In [9]:
df['reason_binary'].unique()

array([0, 1], dtype=int64)

In [11]:
# Create a Counter object
class_counts = Counter(df['reason_binary'])

# Access the counts of each class
for class_label, count in class_counts.items():
    print(f"Class {class_label}: {count} samples")

Class 0: 11702 samples
Class 1: 10728 samples


# TF-IDF with description and title

In [12]:
# Separate features and labels
y = df['reason_binary']
X = df['narrative_tfidf_title']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# Split the remaining data into validation and test sets
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, stratify=y_test, random_state=42)

In [13]:
def train_classifier(dataset, X_train, X_val, y_train, y_val, clf):
    vectorizer = TfidfVectorizer(ngram_range=(1,3), max_df=0.95, min_df=2)
    X_train_tf = vectorizer.fit_transform(X_train)
    X_val_tf = vectorizer.transform(X_val)
    clf.fit(X_train_tf, y_train)
    y_val_pred = clf.predict(X_val_tf)
    
    confusion_mat = confusion_matrix(y_true=y_val, y_pred=y_val_pred, labels=[0,1])
    class_rep= classification_report(y_val, y_val_pred)
    
    print(class_rep)
    print(confusion_mat)
    
    # Create a DataFrame with the original texts, predicted labels, and true labels
    results_df = pd.DataFrame({'narrative_bert_title': dataset.loc[y_val.index, 'narrative_bert_title'],
                               'narrative_tfidf_title': dataset.loc[y_val.index, 'narrative_tfidf_title'],
                               'predicted label': y_val_pred,
                               'true label': y_val})

    misclassified_texts = results_df[results_df['predicted label'] != results_df['true label']]
    
    return misclassified_texts

# KNN

In [15]:
knn_misclassified_texts = train_classifier(df, X_train, X_val, y_train, y_val, KNeighborsClassifier())

              precision    recall  f1-score   support

           0       0.75      0.71      0.73      1755
           1       0.70      0.74      0.72      1609

    accuracy                           0.72      3364
   macro avg       0.72      0.72      0.72      3364
weighted avg       0.72      0.72      0.72      3364

[[1243  512]
 [ 419 1190]]


###  Misclassified texts

In [16]:
knn_misclassified_texts

narrative_bert_title  \
738    ctt - falta de cumprimento na entrega do corre...   
16839  ctt - encomendas internacionais desaparecem um...   
19777  ctt - correio  Eu nao recebo o meu correio há ...   
11659  ctt - reclamação centro de distribuição de alc...   
21868  ctt - encomendas nada ,correio nada ,o que se ...   
...                                                  ...   
20880  ctt - envio de encomenda em correio normal  No...   
7215   Boa Tarde Exmo(s) Venho por este meio solicita...   
21115  Venho por este meio reclamar que até à data nã...   
11903  ctt - encomenda recusada e ainda não devolvida...   
5837   ctt - encomendas do aliexpress não entregues  ...   

                                   narrative_tfidf_title  predicted label  \
738    ctt falta cumprimento entregar correio nuno Ri...                0   
16839  ctt encomenda internacional desaparecer um atr...                1   
19777  ctt correio nao receber correio semana carta s...                0   
11659  ctt reclamação Centro distribuição Alcoitão sa...                1   
21868  ctt encomenda nada correio nada passar venho m...                1   
...                                                  ...              ...   
20880  ctt envio encomenda correio normal passar mês ...                0   
7215   bom tarde exmo s venho meio solicitar esclarec...                1   
21115  venho meio reclamar data recebi três desempreg...                1   
11903  ctt encomenda recusar ainda devolvir bom noite...                1   
5837   ctt encomenda aliexpress entregar bom tarde go...                0   

       true label  
738             1  
16839           0  
19777           1  
11659           0  
21868           0  
...           ...  
20880           1  
7215            0  
21115           0  
11903           0  
5837            1  

[931 rows x 4 columns]

In [17]:
print('MISCLASSIFIED KNN TEXTS')
for i in range(100):
    print(knn_misclassified_texts['narrative_bert_title'].iloc[i])
    print('TRUE LABEL IS {} BUT IT WAS CLASSIFIED AS {}'.format(knn_misclassified_texts['true label'].iloc[i],
                                                                knn_misclassified_texts['predicted label'].iloc[i]))
    print('\n')

MISCLASSIFIED KNN TEXTS
ctt - falta de cumprimento na entrega do correio  eu, Nuno ribeiro, venho por este meio, apresentar o meu descontentamento na entrega tardia da minha correspondência, por parte de alguns carteiros, que não tem condições psicológicas para estarem ao serviço e se desleixam na entrega do correio prejudicando as famílias que recebem apoios do estado para sua sobrevivência. 
TRUE LABEL IS 1 BUT IT WAS CLASSIFIED AS 0


ctt - encomendas internacionais desaparecem umas atrás das outras!  Onde estão as várias encomendas internacionais que fiz e nunca me chegaram a casa? Um mero exemplo entre muitos outros que podia dar, código de registo da encomenda: UC088173604YP esta encomenda chegou a Portugal a 24 de Abril, mas ao destinatário é que ela não chega, ou melhor: elas não chegam! Do que precisam para concluir as encomendas? Motivação? Uma palmadinha nas costas e uma frase amiga: Força vocês conseguem! - hum? Ou talvez precisem de formação para aprender a ser competentes

# XGBoost

In [18]:
xgb_misclassified_texts = train_classifier(df, X_train, X_val, y_train, y_val, XGBClassifier())

              precision    recall  f1-score   support

           0       0.79      0.75      0.77      1755
           1       0.74      0.78      0.76      1609

    accuracy                           0.77      3364
   macro avg       0.77      0.77      0.77      3364
weighted avg       0.77      0.77      0.77      3364

[[1318  437]
 [ 347 1262]]


###  Misclassified texts

In [19]:
xgb_misclassified_texts

narrative_bert_title  \
738    ctt - falta de cumprimento na entrega do corre...   
16839  ctt - encomendas internacionais desaparecem um...   
19777  ctt - correio  Eu nao recebo o meu correio há ...   
11659  ctt - reclamação centro de distribuição de alc...   
21868  ctt - encomendas nada ,correio nada ,o que se ...   
...                                                  ...   
4358   ctt - cartas registadas  No dia 3.01.2020 fui ...   
8500   ctt - encomenda não entregue  Em 21/06 enviei ...   
5184   ctt - endereço incorrecto ou insuficiente  Fiz...   
21115  Venho por este meio reclamar que até à data nã...   
11903  ctt - encomenda recusada e ainda não devolvida...   

                                   narrative_tfidf_title  predicted label  \
738    ctt falta cumprimento entregar correio nuno Ri...                0   
16839  ctt encomenda internacional desaparecer um atr...                1   
19777  ctt correio nao receber correio semana carta s...                0   
11659  ctt reclamação Centro distribuição Alcoitão sa...                1   
21868  ctt encomenda nada correio nada passar venho m...                1   
...                                                  ...              ...   
4358   ctt carta registar dia ctt Fernão ferro entreg...                1   
8500   ctt encomenda entregar enviar encomenda nº irm...                0   
5184   ctt endereço incorrecto insuficiente fiz encom...                1   
21115  venho meio reclamar data recebi três desempreg...                1   
11903  ctt encomenda recusar ainda devolvir bom noite...                1   

       true label  
738             1  
16839           0  
19777           1  
11659           0  
21868           0  
...           ...  
4358            0  
8500            1  
5184            0  
21115           0  
11903           0  

[784 rows x 4 columns]

In [20]:
print('MISCLASSIFIED XGB TEXTS')
for i in range(100):
    print(xgb_misclassified_texts['narrative_bert_title'].iloc[i])
    print('TRUE LABEL IS {} BUT IT WAS CLASSIFIED AS {}'.format(xgb_misclassified_texts['true label'].iloc[i],
                                                                xgb_misclassified_texts['predicted label'].iloc[i]))
    print('\n')

MISCLASSIFIED XGB TEXTS
ctt - falta de cumprimento na entrega do correio  eu, Nuno ribeiro, venho por este meio, apresentar o meu descontentamento na entrega tardia da minha correspondência, por parte de alguns carteiros, que não tem condições psicológicas para estarem ao serviço e se desleixam na entrega do correio prejudicando as famílias que recebem apoios do estado para sua sobrevivência. 
TRUE LABEL IS 1 BUT IT WAS CLASSIFIED AS 0


ctt - encomendas internacionais desaparecem umas atrás das outras!  Onde estão as várias encomendas internacionais que fiz e nunca me chegaram a casa? Um mero exemplo entre muitos outros que podia dar, código de registo da encomenda: UC088173604YP esta encomenda chegou a Portugal a 24 de Abril, mas ao destinatário é que ela não chega, ou melhor: elas não chegam! Do que precisam para concluir as encomendas? Motivação? Uma palmadinha nas costas e uma frase amiga: Força vocês conseguem! - hum? Ou talvez precisem de formação para aprender a ser competentes

# SVC

In [21]:
svc_misclassified_texts = train_classifier(df, X_train, X_val, y_train, y_val, LinearSVC())

              precision    recall  f1-score   support

           0       0.80      0.78      0.79      1755
           1       0.77      0.79      0.78      1609

    accuracy                           0.78      3364
   macro avg       0.78      0.78      0.78      3364
weighted avg       0.78      0.78      0.78      3364

[[1373  382]
 [ 345 1264]]


###  Misclassified texts

In [22]:
svc_misclassified_texts

narrative_bert_title  \
738    ctt - falta de cumprimento na entrega do corre...   
16839  ctt - encomendas internacionais desaparecem um...   
19777  ctt - correio  Eu nao recebo o meu correio há ...   
11659  ctt - reclamação centro de distribuição de alc...   
21868  ctt - encomendas nada ,correio nada ,o que se ...   
...                                                  ...   
7215   Boa Tarde Exmo(s) Venho por este meio solicita...   
17084  ctt - falta de dados  Venho por este meio recl...   
21115  Venho por este meio reclamar que até à data nã...   
11903  ctt - encomenda recusada e ainda não devolvida...   
8441   ctt - entrega não efetuada  No dia 16/07/2020 ...   

                                   narrative_tfidf_title  predicted label  \
738    ctt falta cumprimento entregar correio nuno Ri...                0   
16839  ctt encomenda internacional desaparecer um atr...                1   
19777  ctt correio nao receber correio semana carta s...                0   
11659  ctt reclamação Centro distribuição Alcoitão sa...                1   
21868  ctt encomenda nada correio nada passar venho m...                1   
...                                                  ...              ...   
7215   bom tarde exmo s venho meio solicitar esclarec...                1   
17084  ctt falta dar venho meio reclamar relação enco...                1   
21115  venho meio reclamar data recebi três desempreg...                1   
11903  ctt encomenda recusar ainda devolvir bom noite...                1   
8441   ctt entregar efetuar dia site ctt encomenda ap...                1   

       true label  
738             1  
16839           0  
19777           1  
11659           0  
21868           0  
...           ...  
7215            0  
17084           0  
21115           0  
11903           0  
8441            0  

[727 rows x 4 columns]

In [23]:
print('MISCLASSIFIED SVC TEXTS')
for i in range(100):
    print(svc_misclassified_texts['narrative_bert_title'].iloc[i])
    print('TRUE LABEL IS {} BUT IT WAS CLASSIFIED AS {}'.format(svc_misclassified_texts['true label'].iloc[i],
                                                                svc_misclassified_texts['predicted label'].iloc[i]))
    print('\n')

MISCLASSIFIED SVC TEXTS
ctt - falta de cumprimento na entrega do correio  eu, Nuno ribeiro, venho por este meio, apresentar o meu descontentamento na entrega tardia da minha correspondência, por parte de alguns carteiros, que não tem condições psicológicas para estarem ao serviço e se desleixam na entrega do correio prejudicando as famílias que recebem apoios do estado para sua sobrevivência. 
TRUE LABEL IS 1 BUT IT WAS CLASSIFIED AS 0


ctt - encomendas internacionais desaparecem umas atrás das outras!  Onde estão as várias encomendas internacionais que fiz e nunca me chegaram a casa? Um mero exemplo entre muitos outros que podia dar, código de registo da encomenda: UC088173604YP esta encomenda chegou a Portugal a 24 de Abril, mas ao destinatário é que ela não chega, ou melhor: elas não chegam! Do que precisam para concluir as encomendas? Motivação? Uma palmadinha nas costas e uma frase amiga: Força vocês conseguem! - hum? Ou talvez precisem de formação para aprender a ser competentes

# Embeddings with description and title

In [ ]:
w2v= KeyedVectors.load_word2vec_format('D:\\MS DATA SCIENCE\\NLP TESE\\embeddings\\skip_s600_word2vec.txt')
glove= KeyedVectors.load_word2vec_format('D:\\MS DATA SCIENCE\\NLP TESE\\embeddings\\glove_s600.txt')

In [ ]:
def getVectors(dataset, model_name, number_of_features): 
    # Creating empty dataframe to hold sentences
    W2Vec_Data=pd.DataFrame()
    for review in dataset:
        wordCount=0
        # initiating a sentence with all zeros
        word_Embedding=np.zeros(number_of_features)
        
        # Loop over each word in the review and, if it is in the model's vocaublary, add its feature vector to the total
        for word in word_tokenize(review.lower()): 
            if word in model_name.key_to_index.keys(): # model_w2v.wv.vocab is a list that contains the names of the words in the model's vocabulary
                word_Embedding=word_Embedding+model_name[word] 
                wordCount=wordCount+1
                
        # Appending the sentence to the dataframe
        W2Vec_Data=W2Vec_Data.append(pd.DataFrame([word_Embedding/wordCount]))
    return W2Vec_Data

In [ ]:
import warnings
warnings.filterwarnings("ignore")
# Calling the function to convert all the text data to Word2Vec Vectors
concatenated_w2v=getVectors(df['narrative_embeddings_title'],w2v,600)

# Checking the new representation for sentences
print(concatenated_w2v.shape)
print(concatenated_w2v.head())

In [ ]:
import warnings
warnings.filterwarnings("ignore")
# Calling the function to convert all the text data to Word2Vec Vectors
concatenated_glove=getVectors(df['narrative_embeddings_title'],glove,600)

# Checking the new representation for sentences
print(concatenated_glove.shape)
print(concatenated_glove.head())